### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [JasonHK/Basicfuck#1]
I think you've got "the wrong end of the stick" on the header comments thing.

The point is it's a technique, not something that needs special support in the interpreter; a correctly written interpreter will do them automatically. This is because both commands `[` and `]` will trigger a jump if the current cell value is "right".

Because your loops aren't right, this `Hello World!` doesn't work properly.

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by JasonHK** [comment]
Thanks for your help! I can't found the bug without you. I fixed the bug and the code works now!
![screenshot 01307](https://cloud.githubusercontent.com/assets/4410086/20880351/a12abd02-bb12-11e6-9384-829d587c8d9b.png)
